# Generated by Django 4.1.2 on 2022-11-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_readers_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'awful'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Well')], null=True),
        ),
    ]
